name: Deploy to Firebase Hosting and Functions on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Install dependencies and build the frontend with REACT_APP_BACKEND_URL from GitHub Secrets
      - name: Install and Build Frontend
        working-directory: ./front
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
          FIREBASE_SERVICE_ACCOUNT_BOLDHAIR_F5522: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOLDHAIR_F5522 }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          TYPE: ${{ secrets.TYPE }}
          UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
        run: |
          npm ci
          npm run build

      # Install dependencies for backend (functions)
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      # Deploy both Hosting (frontend) and Functions (backend)
      - name: Deploy to Firebase Hosting and Functions
        working-directory: .  # Set to root where firebase.json is located
        run: firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOLDHAIR_F5522 }}"
